export const testimonialData = [
	{
		id: 1,
		avatar: "./images/person1.jpg",
		text: "The collaboration was top-notch! The design exceeded my expectations and resonated well with our clients. Exceptional understanding of modern trends!",
		stars: "\u2605" + "\u2605" + "\u2605" + "\u2605" + "\u2605",
		name: "Alexander G",
		subtitle: "Brand Strategist",
	},
	{
		id: 2,
		avatar: "./images/person2.jpg",
		text: "The team’s creativity is outstanding! The website is not only beautiful but also highly user-friendly. Our visitors frequently comment on its aesthetic and usability!",
		stars: "\u2605" + "\u2605" + "\u2605" + "\u2605" + "\u2605",
		name: "Catherine P.",
		subtitle: "Interior Designer",
	},
	{
		id: 3,
		avatar: "./images/person3.jpg",
		text: "True professionals! The website design has elevated my brand to a new level. The intuitive navigation captivates users from the first glance.",
		stars: "\u2605" + "\u2605" + "\u2605" + "\u2605" + "\u2605",
		name: "Andrew M.",
		subtitle: "Marketing Specialist",
	},
	{
		id: 4,
		avatar: "./images/person4.jpg",
		text: "Perfectly thought-out approach! The design meets all my requirements and then some. The website creation process was smooth and enjoyable, with an incredible result!",
		stars: "\u2605" + "\u2605" + "\u2605" + "\u2605" + "\u2605",
		name: "Mary S.",
		subtitle: "Lifestyle Blogger",
	},
	{
		id: 5,
		avatar: "./images/person5.jpg",
		text: "It’s always a pleasure to work with professionals. From start to finish, the process was seamless, and the final product is exceptionally high-quality. My clients love it!",
		stars: "\u2605" + "\u2605" + "\u2605" + "\u2605" + "\u2605",
		name: "Victoria L.",
		subtitle: "Restaurant Consultant",
	},
	{
		id: 6,
		avatar: "./images/person6.jpg",
		text: "Impressive work! The website design is elegant, functional, and perfectly aligns with our brand. Highly recommend to anyone who values aesthetics and usability.",
		stars: "\u2605" + "\u2605" + "\u2605" + "\u2605" + "\u2605",
		name: "John D.",
		subtitle: "Fashion Brand Owner",
	},
];
